// import React from "react";

// const LoaPrompt = () => {
//   return <div>Loa Prompt</div>;
// };

// export default LoaPrompt;

import React, { useState } from "react";
import "./loaprompt.css";
import gptLogo from "./assets/chatgpt.svg";
import addBtn from "./assets/add-30.png";
import msgIcon from "./assets/message.svg";
import sendBtn from "./assets/send.svg";
import userIcon from "./assets/user-icon.png";
import gptImgLogo from "./assets/chatgptLogo.svg";
import download from "./assets/download.png";
import { Link } from "react-router-dom";
import SideBar from "../../components/SideBar";
import SidebarTail from "../../components/SidebarTail";
import { BsSend } from "react-icons/bs";
const LoaPrompt = () => {
  const [formData, setFormData] = useState({
    prompt: "",
  });

  const [generatedArticle, setGeneratedArticle] = useState("");

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleEnter = (e) => {
    if (e.key == "Enter") generateArticle();
  };

  const generateArticle = async () => {
    console.log("Generating Article!!");
    try {
      const response = await fetch(
        "https://www.internal.cachelabs.io/api/v1/loa/loa-prompt",
        // "http://localhost:5000/api/v1/loa/loa-prompt",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(formData),
        }
      );

      const data = await response.json();
      console.log(data);

      // Access the generated article from the response
      const generatedArticleText =
        data.choices && data.choices[0] && data.choices[0].message
          ? data.choices[0].message.content
          : "";

      setGeneratedArticle(generatedArticleText);
    } catch (error) {
      console.error("Error:", error);
    }
  };
  return (
    <>
      <SidebarTail />
      <div>
        <div className="App">
          <div className="main ml-[25rem] mt-[10rem]">
            <div className="">
              <div className="inp shadow-md  bg-[#FFFFFF] w-[90rem] h-[5rem] rounded-lg">
                <input
                  className="inpt bg-[#FFFFFF]"
                  type="text"
                  placeholder="Generate an Article"
                  name="prompt"
                  onKeyDown={handleEnter}
                  onChange={handleInputChange}
                />
                <button className="send" onClick={generateArticle}>
                  <BsSend className=" text-secondary w-[2rem] h-[2rem] rotate-45 text-3xl inline-block" />
                </button>
              </div>
            </div>

            {generatedArticle && (
              <div className="chats max-w-[90rem]">
                <div className="chat">
                  <img className="chatImg" src={userIcon} alt="" />
                  <p className="txt">
                    This is an Example Article Generated by a LLM model
                  </p>
                </div>
                <div className="chat bot bg-white shadow-md">
                  <img className="chatImg" src={download} alt="" />
                  <p className="txt">{generatedArticle}</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default LoaPrompt;
