import React, { useState } from "react";
import "./Home.css";
import gptLogo from "./assets/chatgpt.svg";
import addBtn from "./assets/add-30.png";
import msgIcon from "./assets/message.svg";
import sendBtn from "./assets/send.svg";
import userIcon from "./assets/user-icon.png";
import gptImgLogo from "./assets/chatgptLogo.svg";
import download from "./assets/download.png";
import { Link } from "react-router-dom";
import SideBar from "../../components/SideBar";
import SidebarTail from "../../components/SidebarTail";
import Navbar from "../../components/Navbar";
import { BsSend } from "react-icons/bs";
const Home = () => {
  const [formData, setFormData] = useState({
    prompt: "",
  });

  const [generatedArticle, setGeneratedArticle] = useState("");

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleEnter = (e) => {
    if (e.key == "Enter") generateArticle();
  };

  const generateArticle = async () => {
    console.log("Generating Article!!");
    try {
      const response = await fetch(
        "http://15.206.166.198/api/v1/ArticelWriter/articlePrompt",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(formData),
        }
      );

      const data = await response.json();
      console.log(data);

      // Access the generated article from the response
      const generatedArticleText =
        data.choices && data.choices[0] && data.choices[0].message
          ? data.choices[0].message.content
          : "";

      setGeneratedArticle(generatedArticleText);
    } catch (error) {
      console.error("Error:", error);
    }
  };
  return (
    <>
      <SidebarTail />

      <div>
        <div className="App">
          <div className="main">
            {generatedArticle && (
              <div className="chats">
                <div className="chat">
                  <img className="chatImg" src={userIcon} alt="" />
                  <p className="txt">
                    This is an Example Article Generated by a LLM model
                  </p>
                </div>
                <div className="chat bot">
                  <img className="chatImg" src={download} alt="" />
                  <p className="txt">{generatedArticle}</p>
                </div>
              </div>
            )}
            <div className="bg-light-grey w-full  rounded-lg inline-block">
              <input
                className="w-11/12 h-12"
                type="text"
                placeholder="Generate an Article"
                name="prompt"
                onKeyDown={handleEnter}
                onChange={handleInputChange}
              />
              <button
                className="text-xl text-secondary"
                onClick={generateArticle}
              >
                <BsSend className=" text-secondary rotate-45 text-3xl inline-block" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
